version: "3.1"

services:
  api:
    image: ghcr.io/invinsible/kopalka-api:latest
    env_file:
      - .env
    ports:
      - "3100:3000"

        #  photosyn:
#    image: ghcr.io/paaashka/photosyn:latest
#    env_file:
#      - app.env
#    ports:
#      - "8081:8080"
#    depends_on:
#      - imgproxy
#    restart: unless-stopped
