version: "3.1"

services:
  api:
    image: ghcr.io/invinsible/kopalka-api:latest
    env_file:
      - .env
    ports:
      - "3100:3000"

  front:
    image: ghcr.io/invinsible/kopalka-front:latest
    ports:
      - "3101:80"